name: Motore Bot Telegram

on:
  schedule:
    # Esegue lo script tutti i giorni alle 10:00 UTC (le 12:00 in Italia)
    - cron: '0 10 * * *'
  workflow_dispatch: # Questo ti permette di avviarlo anche a mano con un tasto per fare i test

jobs:
  esegui-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Clona il codice
        uses: actions/checkout@v3
        
      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Installa i pacchetti necessari
        run: pip install requests
        
      - name: Avvia il Bot
        run: python bot_partite.py
